완주하지 못한 선수/류동준
Yosseulsin-JOB/algorithm-study-20.08 pull request #10
Opened 2020-09-01 15:04 UTC by rdj94

### 문제 제목

완주하지 못한 선수

## 문제의도 
key value  형태의 dictionary를 사용할수있는지? 문제 유형은 해시로 되어있지만 따로 hash function을 사용할 이유가없다.
물론 dictionary의 동작 구조가 hash Table을 사용하긴한다.
간단하게 key value를 가지는 형태의 dictionary를 선언하고 참가자 리스트의 원소가 키가 되고 중복을 고려하여 +1씩 카운트한다
완주자 리스트의 완주자가 있으면 해당 키값을 -1 하고
최종적으로 dictionary의  키값 value가 0이 아니면 완주를 못한것이므로 value에 해당하는 key를 add하면된다.

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/91867886-15f48600-ecaf-11ea-9aef-f6e40242ece0.png)

### 소요시간 
20분

### 기타 
python의 dictionary type은 key,value의 update가 비교적 자유로운 편이기에 try except의 경우로 나누어서 키값이 있는 경우엔 
카운트 하고 없는경우엔 1로 초기화 하였다. 근데 python의 기본라이브러리 collections의 Counter를 사용하면
방금 말한 iterable한 데이터의 요소를 각기 카운트하여 key ,value형태로 만들어준다. 물론 dict() function을 이용하여 cast를
해주긴 해야한다. 이렇게 함으로써 코드를 좀더 깔끔하게 바꿀수있다.

2020-09-02 10:56 UTC, Sotaneum requested changes
1차 완주하지 못한 선수 수고하셨습니다 👍

2020-09-02 10:56 UTC, Sotaneum commented on 1차/완주하지-못한-선수_류동준.py
> +            pass
이 부분 pass는 불필요한 부분인 것 같아요

2020-09-02 10:56 UTC, Sotaneum commented on 1차/완주하지-못한-선수_류동준.py
> +            pass
try-except 동작보다는 if문으로 개선하는 방향이 좋은 것 같아요

2020-09-02 10:56 UTC, Sotaneum commented on 1차/완주하지-못한-선수_류동준.py
> +    return answer
k를 바로 반환하는게 나을 것 같아요.
`answer` 자체가 상단에서 만들어진 것도 아니고  if문이 성립되지 않을 경우에는 `NameError: name 'answer' is not defined` 오류가 발생하기 때문이죠..

2020-09-05 07:40 UTC, 0113bernoyoun approved these changes

2020-09-05 08:06 UTC, merged