1차 K번째수/류동준
Yosseulsin-JOB/algorithm-study-20.08 pull request #12
Opened 2020-09-01 15:16 UTC by rdj94

### 문제 제목
K 번째 수

### 문제 의도
python의 경우 list sorting과 slice를 알고있으면 문제 없이 풀수있다.
입력으로 list[int, ... , ]과 i,j까지 슬라이싱 할 인덱스  그리고  슬라이싱한 list를 정렬후 k번째 수를 append 하여 반환하면된다.

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/91869987-74226880-ecb1-11ea-9c62-632b4bcb8bd0.png)

### 사용한 테스트 케이스
기본
### 소요 시간
10분
### 기타

2020-09-01 23:24 UTC, Sotaneum requested changes
1차 K번째수 수고하셨습니다 👍

2020-09-01 23:24 UTC, Sotaneum commented on 1차/k번째수_류동준.py
> +    return answer
```suggestion
    return [sorted(array[i-1:j])[k-1] for i,j,k in commands]
```
- 형태로 코드를 줄일 수 있을 것 같아요
- 그리고 i, j, k 변수 보다는 의미 있는 이름으로 변경하는게 좋을 것 같아요.

2020-09-05 08:31 UTC, Sotaneum submitted a review, later dismissed

2020-09-06 06:49 UTC, 0113bernoyoun submitted a review, later dismissed

2020-09-06 07:08 UTC, Sotaneum approved these changes

2020-09-06 07:09 UTC, 0113bernoyoun approved these changes

2020-09-06 07:10 UTC, merged