윤형진 _  K번째 수  코드
Yosseulsin-JOB/algorithm-study-20.08 pull request #14
Opened 2020-09-02 12:30 UTC by 0113bernoyoun

### 문제 제목
[모의고사](https://programmers.co.kr/learn/courses/30/lessons/42748)
### 문제 의도
1. 리스트 슬라이싱을 할 수 있는지
2. 깊은 복사를 할 수 있는지
### 채점 결과
![image](https://user-images.githubusercontent.com/35679738/91981235-793ff000-ed63-11ea-8ffa-89b3b868f39c.png)

### 사용한 테스트 케이스
![image](https://user-images.githubusercontent.com/35679738/91981248-7f35d100-ed63-11ea-915b-68abc51f2589.png)

### 소요 시간
15분
### 기타
copy사용법과 정렬을 어떻게 하는지 까먹어 시간이 걸렸습니다.

2020-09-04 09:28 UTC, Sotaneum requested changes

2020-09-04 09:28 UTC, Sotaneum commented on 1차/윤형진_K번째수.py
> +        answer.append(copied_array[command[2] - 1])
혹시 복사한 이유가 있을까요?

이미 `copied_array = copied_array[command[0] - 1:command[1]]` 부분에서 새로운 객체가 생성되지 않나요?

2020-09-05 07:11 UTC, rdj94 commented on 1차/윤형진_K번째수.py
> +        answer.append(copied_array[command[2] - 1])
일반적으로 list의 원본 데이터는 건드리지 않는것이 하나의 권장되는 규칙중 하나입니다.
물론 여기에서는 그런걸 고려할 필요가 없지만 습관을 들이는것도 나쁘지않다고 생각합니다.
다만 python의 shallow copy의 경우와 deep copy의 경우는 매번 헷갈려서 정리 해놔도 
금방 금방 까먹어서 빡치긴해요

2020-09-06 06:53 UTC, Sotaneum approved these changes

2020-09-06 06:54 UTC, rdj94 approved these changes

2020-09-06 07:04 UTC, merged