add first
Yosseulsin-JOB/algorithm-study-20.08 pull request #20
Opened 2020-09-09 13:57 UTC by rdj94

### 문제 제목
[가운데 글자 가져오기](https://programmers.co.kr/learn/courses/30/lessons/12903)
### 문제 출제 의도
python string slice를 할수 있는지

### 문제 해결 전략
짝수와 홀수일때를 나누어 반환하였음 

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92598734-2b3b6700-f2e4-11ea-9510-90551f34c0a4.png)

### 사용한 테스트 케이스
기본
### 소요 시간
3분

### 문제 제목
[같은 숫자는 싫어](https://programmers.co.kr/learn/courses/30/lessons/12906)

### 문제 출제 의도
stack의 활용 여부

### 문제 해결 전략
빈 stack이 아닐 경우를 고려해 처음 데이터는 무조건 삽입후
그다음 들어올 data와 stack안의 데이터를 비교하며 삽입하였음.

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92598894-6e95d580-f2e4-11ea-9eb9-5dbfe13fba04.png)

### 사용한 테스트 케이스
기본
### 소요 시간
3분

### 문제 제목
소수 찾기

### 문제 출제 의도
에라토네스의 체를 아는지? 혹은 소수를 찾는데 있어서 특정 규칙을 알고 있는지?

### 문제 해결 전략
단순 for range(1,n+1)까지의 데이터를 나머지 연산해가며 풀었지만 효율성 체크에서 실패하여서
소수가 가지는 특징에 대한 자료를 찾아보았음.
1. 특정 value n의 약수는 최대값이 n/2이다.
2. 특정 value n의 약수는 제곱근 보다 작다.
3. 소수의 배수는 약수이다.

위의 두 전략을 사용하여  문제를 푸는데있어서  1번은 효율성 체크에 실패하였고
2번의 경우  n의 최대 약수가 sqrt(n) 이하이므로 i=sqrt(n)까지 검사 하는 케이스에 있어서 
5일경우는 실패하는 경우가 생김 사실 시작 배열을 3으로 두면 상관없다.
3의 경우 소수가 첫열은 2, 3,5,7,11,13 순으로 가는것을 주목하여
3,5,7 순으로 n까지 만드는 배열 생성후 소수의 배수를 거르고 소수 2에 대한 +1 연산을 해주었음

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92605400-a739ad00-f2ec-11ea-8875-059692bb948b.png)
![image](https://user-images.githubusercontent.com/24598628/92605419-abfe6100-f2ec-11ea-90e0-d18033ace234.png)

### 사용한 테스트 케이스
기본
### 소요 시간
30분

### 문제 제목
[시저 암호](https://programmers.co.kr/learn/courses/30/lessons/12926)
### 문제 출제 의도
문자열 쉬프트를 할수있는지

### 문제 해결 전략
1. alphabet을 index화해서 숫자로 맵핑하였음
2. 맵핑된 숫자를  +n만큼 더하고 알파벳 숫자 % 26을 하고  index의 맞는 문자열에 대해 join하였다.

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92606861-6773c500-f2ee-11ea-873b-a2785069e368.png)

### 사용한 테스트 케이스
기본
### 소요 시간
30분

### 문제 제목
[약수의 합](https://programmers.co.kr/learn/courses/30/lessons/12928)

### 문제 출제 의도
나머지 연산을 할수있는지

### 문제 해결 전략
그냥 1부터 n까지 나눠가며 나머지 연산이 0일때 더하면된다.

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92607519-334cd400-f2ef-11ea-9a54-f2642ab55cf9.png)

### 사용한 테스트 케이스
기본
### 소요 시간
5분

### 문제 제목
[정수 제곱근판별](https://programmers.co.kr/learn/courses/30/lessons/12934)

### 문제 출제 의도
제곱근을 리턴하는것

### 문제 해결 전략
python의 pow를 사용할수 있는지

### 채점 결과
![image](https://user-images.githubusercontent.com/24598628/92607992-c980fa00-f2ef-11ea-84c8-b420c87f4807.png)

### 사용한 테스트 케이스
기본본
### 소요 시간
5분
### 기타

2020-09-09 15:09 UTC, Sotaneum requested changes
파일명 양식에 맞게 변경해주세요.

2020-09-12 23:32 UTC, Sotaneum requested changes
2차 수고하셨습니다 : )

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_가운데-글자-가져오기.py
> +        return s[n]
```suggestion
    n = int(len(s) / 2)
    return s[n-1:n+1] if len(s) % 2 == 0 else s[n]
```

- n = int(len(s) / 2) 이 코드가 중복으로 들어가기 때문에 위로 분리하는게 좋을 것 같습니다.
- 반환되는 건 len(s) % == 0 값에 따라 달라지기 때문에 하나로 표현하는 것이 좋을 것 같습니다.

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_소수-찾기.py
> +    for i in range(2, m + 1):
이 부분은 n이 10000 이면 100까지만 검사한다는 거죠? 
그런데 이해가 잘 안되는 부분이 10000까지의 숫자 중에서 100까지 나온 소수로 모두 커버가 가능하다는 걸까요?
이해가 잘 안됩니다.

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_시저-암호.py
> +    alphabets = OrderedDict(zip(string.ascii_lowercase,range(1,27)))
신기한 함수들 많이 아시네요 ㅋㅋㅋㅋㅋㅋ

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_시저-암호.py
> +            result.append(tmp)
```suggestion
            result.append(tmp.upper() if c.isupper() else tmp.lower())
```
어처피 문자열에서 lower와 upper 둘 중 하나이기 때문에 if-elif로 묶을 필요가 없을 듯 해요

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_정수-제곱근-판별.py
> +        return -1
사실 if - else 보다  `true if else false` 형태가 더 좋은 것인지는 모르겠으나 보통 후자를 선택하더라구요
```suggestion
    return pow(value+1,2) if int(value) == value else -1
```

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_정수-제곱근-판별.py
> +    return value
보통 값을 저장 후에 반환하던가요? (개인적인 질문)
```suggestion
    return check(n)
```

2020-09-12 23:32 UTC, Sotaneum commented on 2차/류동준_같은-숫자는-싫어.py
> +                answer.append(data)
javascript에서만 그런건지는 모르겠는데 보통 if - else 보다는 if / if 형태가 좋을 것 같아요

```suggestion
        if not answer:
            answer.append(data)
            continue

        if not answer[-1] == data:
            answer.append(data)            
```

2020-09-13 11:09 UTC, Sotaneum approved these changes

2020-09-13 12:55 UTC, 0113bernoyoun approved these changes

2020-09-13 14:19 UTC, merged