1차 모의고사
Yosseulsin-JOB/algorithm-study-20.08 pull request #4
Opened 2020-09-01 12:37 UTC by 0113bernoyoun

### 문제 제목
[모의고사](https://programmers.co.kr/learn/courses/30/lessons/42840)
### 문제 의도
1. 각 패턴을 도입할 수 있는지

### 채점 결과
![image](https://user-images.githubusercontent.com/35679738/91851845-dae85780-ec9a-11ea-9d0b-be4acd2f7d8f.png)

### 사용한 테스트 케이스
![image](https://user-images.githubusercontent.com/35679738/91852064-3dd9ee80-ec9b-11ea-848e-b0ce7001d354.png)

### 소요 시간
30분
### 기타

2020-09-01 13:50 UTC, Sotaneum requested changes
1차 모의고사 수고하셨습니다 👍

2020-09-01 13:50 UTC, Sotaneum commented on 1차/윤형진_모의고사.py
> +    score = 0
이 변수는 불필요한 변수가 아닌가요 ?

2020-09-01 13:50 UTC, Sotaneum commented on 1차/윤형진_모의고사.py
> +        students_score.append(score)
```suggestion
    for student_pattern in students_pattern:
        k = 0
        score = 0

        for answer in answers:

            if k == len(student_pattern):
                k = 0

            if answer == student_pattern[k]:
                score = score + 1

            k = k + 1

        students_score.append(score)
```

- 매번 idx로 접근하기 보다는 for-in 문을 좀 더 효율적으로 사용하면 좋을 것 같아요

2020-09-02 03:18 UTC, rdj94 commented
수고용

2020-09-05 07:34 UTC, 0113bernoyoun commented on 1차/윤형진_모의고사.py
> +    score = 0
아 그러네요 중복 선언 했습니다 푸는데 급급하다 보니 코드 품질에 대해 신경을 쓰지 못했네요 다음 부터는 신경 쓰도록 하겠습니다 감사합니다~

2020-09-05 07:35 UTC, 0113bernoyoun commented on 1차/윤형진_모의고사.py
> +        students_score.append(score)
확실히 더 간결해지네요

2020-09-05 08:25 UTC, Sotaneum approved these changes

2020-09-05 08:26 UTC, rdj94 approved these changes

2020-09-05 08:27 UTC, merged