1차 체육복
Yosseulsin-JOB/algorithm-study-20.08 pull request #7
Opened 2020-09-01 13:21 UTC by 0113bernoyoun

### 문제 제목
[모의고사](https://programmers.co.kr/learn/courses/30/lessons/42862)
### 문제 의도
1. 문제를 정확히 해석할 수 있는지(여분을 가져온 학생도 도난당할 수 있다는 점)
2. 맨 앞사람과 맨 뒷사람의 경우에 대해 처리가 가능한지
### 채점 결과
![image](https://user-images.githubusercontent.com/35679738/91856284-551bda80-eca1-11ea-8fb2-5e554c8251d8.png)

### 사용한 테스트 케이스
![image](https://user-images.githubusercontent.com/35679738/91856317-606f0600-eca1-11ea-953d-24a76895dc09.png)

### 소요 시간
35분
### 기타
문제를 정확히 읽지 않으면 통과할 수 없는 문제였습니다. 제가 고생했습니다.

2020-09-01 13:39 UTC, Sotaneum requested changes
1차 체육복 고생하셨습니다 ~ 👍

2020-09-01 13:39 UTC, Sotaneum commented on 1차/윤형진_체육복.py
> +                    student_list[i] = 0
```suggestion
            if i > 0 and student_list[i - 1] == 1 :
                student_list[i - 1] = 0
                student_list[i] = 0
            elif  i < n - 1 and student_list[i + 1] == 1 : 
                student_list[i + 1] = 0
                student_list[i] = 0
```

- 앞 부터 검사를 진행하기 때문에 현재 위치에서 뒤에있는 값을 먼저 검사하는게 최적인 방법이라 생각합니다.
- 이 가정을 통해 코드를 효과적으로 줄일 수 있을 것 같아요.
- 혹시 이 부분에 대해 반례가 있다면 말해주세요 ~

2020-09-01 13:39 UTC, Sotaneum commented on 1차/윤형진_체육복.py
> +        if i == 0 or i == 1 :
```suggestion
        if i >= 0 :
```
- i == 0 or i == 1 으로 처리하는 것보다 i >= 0가 더 가독성 있어 보입니다. 
- 혹은 if i != -1 도 괜찮아 보이네요.
- 이러한 방식이 가능한 이유는 각 학생마다 예비를 1개만, 놓고오는것도 1개만 가능하기 때문입니다.

2020-09-05 07:07 UTC, rdj94 approved these changes, later dismissed
고생하셨습니다.

2020-09-05 11:07 UTC, 0113bernoyoun commented on 1차/윤형진_체육복.py
> +                    student_list[i] = 0
참고하겠습니다 감사합니다~~

2020-09-05 11:07 UTC, 0113bernoyoun commented on 1차/윤형진_체육복.py
> +        if i == 0 or i == 1 :
아 그 부분은 생각하지 못했네요 감사합니다

2020-09-05 11:18 UTC, Sotaneum approved these changes

2020-09-05 11:20 UTC, rdj94 approved these changes

2020-09-05 11:20 UTC, merged